name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
    - uses: actions/checkout@v4
    - name: Set up QEMU
    - uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
    - uses: docker/setup-buildx-action@v3
    - name: Build the Docker image
      run: docker buildx build . --file Dockerfile --platform linux/amd64 --platform linux/arm64 --tag pb-ip-monitor:$(date +%s)
